import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/src/components/Sidebar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sidebarLinks = [
  { label: "Início", href: "/" },
  { label: "Clientes", href: "/clientes" },
  { label: "Produtos", href: "/produtos" },
  { label: "Pedidos", href: "/pedidos" },
  { label: "Histórico", href: "/historico" },
  { label: "Sobre", href: "/sobre" },
]

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-br"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>

        <div className="flex p-4">
          <Sidebar links={sidebarLinks}
          />
          <main>{children}</main>
        </div>
        
      </body>
    </html>
  );
}
