import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/src/components/Sidebar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sidebarLinks = [
  { label: "Início", href: "/" },
  { label: "Clientes", href: "/clientes" },
  { label: "Novo Cliente", href: "/clientes/novo" },
  { label: "Produtos", href: "/produtos" },
  { label: "Novo Produto", href: "/produtos/novo" },
  { label: "Novo Pedido", href: "/pedidos" },
  { label: "Histórico De Pedidos", href: "/historicoPedidos" },
  { label: "Sobre", href: "/sobre" },
  { label: "Testes", href: "/testes" },
]

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-BR"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>

        <div className="flex p-4 min-h-screen">
          <div className="sticky top-4 h-fit">
            <Sidebar links={sidebarLinks}
            />
          </div>
          <main className="flex-1 p-1">{children}</main>
        </div>
        
      </body>
    </html>
  );
}
